org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
loom.mixin.useLegacyMixinAp=false
loom.platform=neoforge

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
neo_forge_version=21.1.111

mod_version=0.3.2-devel
maven_group=dev.tizu.hexcessible
archives_base_name=hexcessible

hexcasting_version=0.12.0-devel-pre-39
cloth_config_version=15.0.130
patchouli_version=1.21.1-92-NEOFORGE
architectury_version=13.0.8
forge_kotlin_version=5.12.0
paucal_version=0.7.1-pre-27
inline_version=1.2.2
caelus_version=7.0.1+1.21.1
mixinextras_version=0.5.0
jetbrains_annotations_version=24.1.0
