modLoader = "javafml"
loaderVersion = "[4,)"
license = "The JSON License"

[[mods]]
modId = "hexcessible"
version = "${version}"
displayName = "Hexcessible"
logoFile = "assets/hexcessible/icon.png"
authors = "Ruby (tizu), ElNico56"
description = "Hex Casting, with a bit more accessibility sprinkled on top."
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "hexcessible.mixins.json"

[[dependencies.hexcessible]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.111,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hexcessible]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hexcessible]]
modId = "hexcasting"
type = "required"
versionRange = "[0.12.0-devel-pre-35,)"

ordering = "AFTER"
side = "CLIENT"

[[dependencies.hexcessible]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.130,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.hexcessible]]
modId = "patchouli"
type = "required"
versionRange = "[1.21.1-92,)"
ordering = "AFTER"
side = "CLIENT"
